### ISSUE TITLE
Query regarding estimation of sparse factor loadings

### ISSUE THREAD

**Issue by CosmoLuminous** [lee-jaejoon/robust-sparse-bayesian-infinite-factor-models#1]
Hi Lee,

I just wanted to ask that, is there a possibility in this implementation through which we can get sparse factor loadings instead of estimating the covariance matrix?

**Comment by lee-jaejoon** [comment]
Hi,

Posterior samples of factor loadings can be obtained by option `linearMGSP_t( ... , output = c("factSamples"), ... )`.

However, this Bayesian factor model is designed to perform covariance estimation, thus does not have any constraint for identifiability of factor loadings. You need to perform additional post-processing before any interpretation on posterior samples of factor loadings.

**Comment by CosmoLuminous** [comment]
Thank you for the details.
